export const Icons = {
  categories: require('../assets/icons/categories.png'),
  earn_points: require('../assets/icons/earn_points.png'),
  favourite: require('../assets/icons/favourite.png'),
  universe: require('../assets/icons/universe.png'),
  camera: require('../assets/icons/camera.png'),
  gallery: require('../assets/icons/gallery.png'),
  my_hub: require('../assets/icons/my_hub.png'),
  show: require('../assets/icons/show.png'),
  hidden: require('../assets/icons/hidden.png'),
  check: require('../assets/icons/check.png'),
  right_arrow: require('../assets/icons/right_arrow.png'),
  left_arrow: require('../assets/icons/left_arrow.png'),
  location: require('../assets/icons/location.png'),
  location2: require('../assets/icons/location2.png'),
  notification: require('../assets/icons/notification.png'),
  navigation: require('../assets/icons/navigation.png'),
  search: require('../assets/icons/search.png'),
  points: require('../assets/icons/points.png'),
  wallet: require('../assets/icons/wallet.png'),
  cancel: require('../assets/icons/cancel.png'),
  down_arrow: require('../assets/icons/down_arrow.png'),
  filter: require('../assets/icons/filter.png'),
  share: require('../assets/icons/share.png'),
  location_point: require('../assets/icons/location_point.png'),
  heart: require('../assets/icons/heart.png'),
  distance: require('../assets/icons/distance.png'),
  beauty_and_spa: require('../assets/icons/beauty_and_spa.png'),
  car: require('../assets/icons/car.png'),
  dessert: require('../assets/icons/dessert.png'),
  eat: require('../assets/icons/eat.png'),
  entertainment: require('../assets/icons/entertainment.png'),
  food_trucks: require('../assets/icons/food_trucks.png'),
  happy: require('../assets/icons/happy.png'),
  home_service: require('../assets/icons/home_service.png'),
  island: require('../assets/icons/island.png'),
  professional_services: require('../assets/icons/professional_services.png'),
  store: require('../assets/icons/store.png'),
  wellness: require('../assets/icons/wellness.png'),
  map: require('../assets/icons/map.png'),
  call: require('../assets/icons/call.png'),
  bed: require('../assets/icons/bed.png'),
  close: require('../assets/icons/close.png'),
  list: require('../assets/icons/list.png'),
  maximize: require('../assets/icons/maximize.png'),
  minus: require('../assets/icons/minus.png'),
  plus: require('../assets/icons/plus.png'),
  minimize: require('../assets/icons/minimize.png'),
  discount: require('../assets/icons/discount.png'),
  bathtub: require('../assets/icons/bathtub.png'),
  heart2: require('../assets/icons/heart2.png'),
  heart3: require('../assets/icons/heart3.png'),
  heart4: require('../assets/icons/heart4.png'),
  property: require('../assets/icons/property.png'),
  hospital: require('../assets/icons/hospital.png'),
  share2: require('../assets/icons/share2.png'),
  about: require('../assets/icons/about.png'),
  checkmark_badge: require('../assets/icons/checkmark_badge.png'),
  inbox: require('../assets/icons/inbox.png'),
  logout: require('../assets/icons/logout.png'),
  loyalty_card: require('../assets/icons/loyalty_card.png'),
  my_deals: require('../assets/icons/my_deals.png'),
  preference: require('../assets/icons/preference.png'),
  user_group: require('../assets/icons/user_group.png'),
  user: require('../assets/icons/user.png'),
  arrow_right2: require('../assets/icons/arrow_right2.png'),
  arrow_left: require('../assets/icons/arrow_left.png'),
  hide: require('../assets/icons/hide.png'),
  visible: require('../assets/icons/visible.png'),
  calender: require('../assets/icons/calendar.png'),
  edit: require('../assets/icons/edit.png'),
  tick: require('../assets/icons/tick.png'),
  tick2: require('../assets/icons/tick2.png'),
  shower: require('../assets/icons/shower.png'),
  groups: require('../assets/icons/groups.png'),
  share3: require('../assets/icons/share3.png'),
  arrow_left2: require('../assets/icons/arrow_left2.png'),
  heart1: require('../assets/icons/heart1.png'),
  location1: require('../assets/icons/location1.png'),
  share4: require('../assets/icons/share4.png'),
  sleep: require('../assets/icons/sleep.png'),
  arrow_up_right: require('../assets/icons/arrow-up-right.png'),
  direction: require('../assets/icons/direction.png'),
  global: require('../assets/icons/global.png'),
  call2: require('../assets/icons/call2.png'),
  info: require('../assets/icons/info.png'),
  tick1: require('../assets/icons/tick1.png'),
  gift_active: require('../assets/icons/gift_active.png'),
  gift_card: require('../assets/icons/gift_card.png'),
  gift_deactive: require('../assets/icons/gift_deactive.png'),
  polygon: require('../assets/icons/polygon.png'),
  x: require('../assets/icons/x.png'),
  copy: require('../assets/icons/copy.png'),
  email: require('../assets/icons/email.png'),
  facebook: require('../assets/icons/facebook.png'),
  linkedin: require('../assets/icons/linkedin.png'),
  whatsapp: require('../assets/icons/whatsapp.png'),
  down_arrow2: require('../assets/icons/down_arrow2.png'),
  question: require('../assets/icons/question.png'),
  IcLoyaltyPoints: require('../assets/icons/ic_loyalty_points.png'),
  IcTourism: require('../assets/icons/ic_tourism.png'),
  IcBadge: require('../assets/icons/ic_badge.png'),
  bin: require('../assets/icons/bin.png'),
};

export const Images = {
  logo: require('../assets/images/logo.png'),
  shadow_arrow: require('../assets/images/shadow_arrow.png'),
  img1: require('../assets/images/img1.png'),
  img2: require('../assets/images/img2.png'),
  img3: require('../assets/images/img3.png'),
  img4: require('../assets/images/img4.png'),
  img5: require('../assets/images/img5.png'),
  img6: require('../assets/images/img6.png'),
  img7: require('../assets/images/img7.png'),
  img8: require('../assets/images/img8.png'),
  img9: require('../assets/images/img9.png'),
  img10: require('../assets/images/img10.png'),
  img11: require('../assets/images/img11.png'),
  img12: require('../assets/images/img12.png'),
  img13: require('../assets/images/img13.png'),
  img14: require('../assets/images/img14.png'),
  img15: require('../assets/images/img15.png'),
  img16: require('../assets/images/img16.png'),
  brand_logo: require('../assets/images/brand_logo.png'),
  user: require('../assets/images/user.png'),
  hawthorne: require('../assets/images/hawthorne.png'),
  logo1: require('../assets/images/logo1.png'),
  img17: require('../assets/images/img17.png'),
  img18: require('../assets/images/img18.png'),
  img19: require('../assets/images/img19.png'),
  img20: require('../assets/images/img20.png'),
  img21: require('../assets/images/img21.png'),
  img22: require('../assets/images/img22.png'),
  img23: require('../assets/images/img23.png'),
  img24: require('../assets/images/img24.png'),
  logo2: require('../assets/images/logo2.png'),
  mapImage: require('../assets/images/mapImage.png'),
  rectangle: require('../assets/images/rectangle.png'),
  union: require('../assets/images/union.png'),
  badges: require('../assets/images/badges.png'),
  u1: require('../assets/images/u1.png'),
  u2: require('../assets/images/u2.png'),
  u3: require('../assets/images/u3.png'),
  u4: require('../assets/images/u4.png'),
  u5: require('../assets/images/u5.png'),
  img25: require('../assets/images/img25.png'),
  shodow_arrow2: require('../assets/images/shodow_arrow2.png'),
  no_image: require('../assets/images/no_image.png'),
  gimmziBadge: require('../assets/images/gimmziBadge.png'),
  gimmziBadgeLogo: require('../assets/images/gimmziBadgeLogo.png'),
  gimmziLogo: require('../assets/images/gimmziLogo.png'),
  
};

export const Colors = {
  white: '#FFFFFF',
  black: '#000',
  dark: '#182230',
  mist_blue: '#667085',
  elephant: '#1B3140',
  iron: '#D0D5DD',
  carmine_pink: '#EB3D4D',
  ball_blue: '#26A1D6',
  pale_sky: '#707781',
  picton_blue: 'rgba(82, 181, 222, 0.10)',
  brick_red: '#CD2C4E',
  santa_grey: '#98A2B3',
  dawn_pink: '#EAECF0',
  river_bed: '#475467',
  green: '#17B26A',
  white_ice: '#DBFAE6',
  cyne_blue: 'rgba(24, 34, 48, 0.32)',
  mikado_yellow: '#F9C80E',
  catskill_white: '#F2F4F7',
  pickled_bluewood: '#344054',
  pearl: '#FEECEE',
  tropical_blue: '#BCE2F2',
  water: '#E9F6FB',
  mirage: '#101828',
  alabaster: '#F9FAFB',
  catskill_white: '#F2F4F7CC',
  milk_white: '#FCFCFD',
  moonraker: '#C7D3EB',
  flat_blue: '#3174A5',
  smoke: '#F5F5F5',
  mango_tango: '#F06804',
  red: '#FF0505',
  neutral: '#808080',
};

export const Fonts = {
  InterBold: 'Inter-Bold',
  InterRegular: 'Inter-Regular',
  InterSemiBold: 'Inter-SemiBold',
  InterMedium: 'Inter-Medium',
};

export const IamgesUri = {
  img4: 'https://i.postimg.cc/RCkB3fyq/img4.png',
  img6: 'https://i.postimg.cc/7LVcmJK1/img6.png',
  img7: 'https://i.postimg.cc/h43kkxcp/img7.png',
  img8: 'https://i.postimg.cc/DzFdjCNH/img8.png',
  img9: 'https://i.postimg.cc/3W5DyN5V/img9.png',
  img10: 'https://i.postimg.cc/zGk0rZT8/img10.png',
  img11: 'https://i.postimg.cc/9f709V1j/img11.png',
  img12: 'https://i.postimg.cc/1RHtwv04/img12.png',
  img13: 'https://i.postimg.cc/fLsz0dJx/img13.png',
  img15: 'https://i.postimg.cc/K8TJs38k/img15.png',
  img16: 'https://i.postimg.cc/rsbNfq6N/img16.png',
};

export function hexToRGB(hex, opacity = 1, defaultColor = 'red') {
  var c;
  if (/^#([A-Fa-f0-9]{3}){1,2}$/.test(hex)) {
    c = hex.substring(1).split('');
    if (c.length == 3) {
      c = [c[0], c[0], c[1], c[1], c[2], c[2]];
    }
    c = '0x' + c.join('');
    return (
      'rgba(' +
      [(c >> 16) & 255, (c >> 8) & 255, c & 255].join(',') +
      ',' +
      opacity +
      ')'
    );
  }
  return defaultColor;
}
